In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from base_dreams_session import agyw_service_session, agyw_service_hivinfo, mastersheet

In [2]:
agyw_service_session

,Code,last_name,first_name,dob,age,nbre_session,number_of_different_topic_for_inter,id_patient,number_of_session_sensiblisation_08_for_all_time,number_of_session_sensiblisation_10_for_all_time,number_of_session_sensiblisation_11_for_all_time,number_of_session_sensibilisation_18_for_all_time,number_of_session_sensibilisation_08_for_inter,number_of_session_sensibilisation_10_for_inter,number_of_session_sensibilisation_11_for_inter,number_of_session_sensibilisation_18_for_inter,interview_date
0,CAP/DRMS/022007805,Joseph,Berlandine,2005-05-28,16,8,8.0,65440,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2020-03-09
1,PAP/DRMS/032035601,François,Accla,2005-12-06,15,17,3.0,74866,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2020-06-10
2,PAP/DRMS/032035602,Pierre,Adassa,2010-05-10,11,17,3.0,74867,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2020-07-12
3,GON/DRMS/047042401,dumas,Guerdine,2002-11-23,18,17,17.0,74958,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,2020-07-30
4,PAP/DRMS/032035603,Derilus,Wesnaika,2009-11-14,11,17,3.0,74970,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2020-06-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11286,PAP/DRMS/032302815,Louis,Stamany,2000-02-04,21,18,18.0,123923,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2021-07-27
11287,PAP/DRMS/032302816,Charles,bethana,2002-09-04,19,18,18.0,123924,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2021-07-26
11288,PAP/DRMS/032302817,victor,mitrose,2000-07-24,21,18,18.0,123925,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2021-08-16
11289,PAP/DRMS/032302818,st cyr,edline,1999-02-08,22,18,18.0,123926,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2021-07-18
11290,PAP/DRMS/032302819,Alcius,Stecie,2007-07-04,14,18,18.0,123927,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2021-07-13

In [3]:
agyw_service_hivinfo

,Code,last_name,first_name,dob,age,test_date,condoms_reception_date,vbg_treatment_date,gynecological_care_date,prep_initiation_date,has_been_sensibilize_for_condom,score,enrollement_date,is_muso,is_gardening
0,PAP/DRMS/004005408,Jumeau,Jennifer,2004-05-25,17,0000-00-00,2021-06-25,0000-00-00,None,None,NaN,31,2020-01-31,no,no
1,PAP/DRMS/004005410,Louis,Mykalexia,2002-04-11,19,0000-00-00,2021-05-09,0000-00-00,None,None,NaN,19,2020-01-31,no,no
2,PAP/DRMS/032035602,Pierre,Adassa,2010-05-10,11,0000-00-00,0000-00-00,0000-00-00,None,None,NaN,44,2020-07-12,yes,no
3,CAP/DRMS/100071305,Docteur,Hershline,2005-10-02,15,0000-00-00,2020-07-10,0000-00-00,None,None,NaN,41,2020-06-04,no,yes
4,CAP/DRMS/100071306,Ambroise,stecie,2003-07-02,18,0000-00-00,2020-07-10,0000-00-00,None,None,NaN,31,2020-06-04,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4138,PAP/DRMS/032302816,Charles,bethana,2002-09-04,19,2021-08-10,2021-08-10,0000-00-00,None,0000-00-00,1.0,26,2021-07-26,no,no
4139,PAP/DRMS/032302817,victor,mitrose,2000-07-24,21,2021-08-10,2021-08-10,0000-00-00,None,0000-00-00,1.0,34,2021-08-16,no,no
4140,PAP/DRMS/032302818,st cyr,edline,1999-02-08,22,2021-08-10,2021-08-10,0000-00-00,None,0000-00-00,1.0,15,2021-07-18,no,no
4141,PAP/DRMS/032302819,Alcius,Stecie,2007-07-04,14,2021-08-10,2021-08-10,0000-00-00,None,0000-00-00,1.0,25,2021-07-13,no,no
4142,PAP/DRMS/035018213,Jovin,Fabiola,2000-02-03,21,2021-09-11,0000-00-00,0000-00-00,None,0000-00-00,0.0,28,2020-08-29,no,no

In [4]:
mastersheet

,main_id,muso_eligibility,actual_id_group,group_she_take_sessions,code,last_name,first_name,dob,age,number_of_different_topic,...,cf_25,cm_18_24,cm_25,created_at,updated_at,created_by,updated_by,score,enrollement_date,organisation
0,0,no17,1895,None,None,None,None,None,NaN,NaN,...,NaN,NaN,NaN,NaT,None,NaN,NaN,30,2020-07-09,CARIS
1,51353,no17,1,"1,",PAP/DRMS/001000101,Altidor,Osline Altidor,2004-11-23,16.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,27,2019-12-18,CARIS
2,51354,yes_sup18,1,"1,",PAP/DRMS/001000102,Exume,Fafane,2002-04-11,19.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,46,2019-12-18,CARIS
3,51355,no18,1,"1,",PAP/DRMS/001000103,Derosier,Sonnette,2000-12-08,20.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,34,2019-12-18,CARIS
4,51356,yes_sup18,1,"1,",PAP/DRMS/001000104,pierre,chilove,2002-04-04,19.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,24,2019-12-18,CARIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29798,123923,no18,3028,"3028,",PAP/DRMS/032302815,Louis,Stamany,2000-02-04,21.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,56,2021-07-27,Caris
29799,123924,no18,3028,"3028,",PAP/DRMS/032302816,Charles,bethana,2002-09-04,19.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,26,2021-07-26,Caris
29800,123925,no18,3028,"3028,",PAP/DRMS/032302817,victor,mitrose,2000-07-24,21.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,34,2021-08-16,Caris
29801,123926,no18,3028,"3028,",PAP/DRMS/032302818,st cyr,edline,1999-02-08,22.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,15,2021-07-18,Caris
29802,123927,no17,3028,"3028,",PAP/DRMS/032302819,Alcius,Stecie,2007-07-04,14.0,18.0,...,NaN,NaN,NaN,NaT,None,NaN,NaN,25,2021-07-13,Caris